version: 2.1
jobs:
  install_postgresql_client:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Update and Clean APT
          command: |
            sudo apt-get update
            sudo apt-get clean
      - run:
          name: Install PostgreSQL Client
          command: |
            sudo apt-get install -y postgresql-client
workflows:
  version: 2
  install_and_test:
    jobs:
      - install_postgresql_client