name: Ruby on Rails CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://rails:password@localhost:5432/rails_test
      DISABLE_SPRING: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Prepare database
        run: bin/rails db:prepare

      - name: Run test suite
        run: bin/rake

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Generate binstubs
        run: bundle binstubs bundler-audit brakeman rubocop

      - name: Audit gems
        run: bin/bundler-audit --update

      - name: Scan security issues
        run: bin/brakeman -q -w2

      - name: RuboCop
        run: bin/rubocop --parallel
